BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Cases" (
	"c1控制碼"	INTEGER,
	"c2法院"	TEXT NOT NULL,
	"c3案號_年"	INTEGER,
	"c4案號_字別"	TEXT,
	"c5案號_號"	INTEGER,
	"c6案由"	TEXT,
	"c7法官名1"	TEXT,
	"c8法官名2"	TEXT,
	"c9法官名3"	TEXT,
	"c10原審法院"	TEXT,
	"c11原審案號_年"	INTEGER,
	"c12原審案號_字別"	INTEGER,
	"c13原審案號_號"	INTEGER,
	"c14全案終結日期_年"	INTEGER,
	"c15全案終結日期_月"	INTEGER,
	"c16全案終結日期_日"	INTEGER,
	"c17全案終結情形"	TEXT,
	"c18得上訴"	REAL,
	"c19不得上訴"	REAL,
	"c20得抗告"	REAL,
	"c21不得抗告"	REAL,
	"c22自訴人是否有律師代理"	INTEGER,
	"c23裁判內容出現_消除對婦女一切形式歧視公約"	INTEGER,
	"c24裁判內容出現_兒童權利公約"	INTEGER,
	"c25裁判內容出現_兩人權公約"	INTEGER,
	"c26裁判內容出現_身心障礙者權利公約"	INTEGER,
	"c27犯選罷法終結選舉類別"	INTEGER,
	"c28裁判書ID"	TEXT NOT NULL,
	"Case_ID"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("Case_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SpecialCommutation" (
	"sr1控制碼"	INTEGER,
	"sr2量刑特殊減輕"	TEXT,
	"Charge_ID"	INTEGER,
	FOREIGN KEY("Charge_ID") REFERENCES "Charges"("Charge_ID")
);
CREATE TABLE IF NOT EXISTS "SpecialAggravation" (
	"sa1控制碼"	INTEGER,
	"sa2量刑特殊加重"	TEXT,
	"Charge_ID"	INTEGER,
	FOREIGN KEY("Charge_ID") REFERENCES "Charges"("Charge_ID")
);
CREATE TABLE IF NOT EXISTS "Defendants" (
	"d1控制碼"	INTEGER,
	"d2被告終結日期_年"	INTEGER,
	"d3被告終結日期_月"	INTEGER,
	"d4被告終結日期_日"	INTEGER,
	"d5辯護及代理"	TEXT,
	"d6保安處分_感化教育"	INTEGER,
	"d7保安處分_監護"	INTEGER,
	"d8保安處分_禁戒"	INTEGER,
	"d9保安處分_強制工作"	INTEGER,
	"d10保安處分_保護管束"	INTEGER,
	"d11保安處分_強制治療"	INTEGER,
	"d12保安處分_驅逐出境"	INTEGER,
	"d13保安處分_安置輔導"	INTEGER,
	"d14保安處分_其他"	INTEGER,
	"d15裁判程序"	TEXT,
	"d16協商賠償支付對象_被害人"	INTEGER,
	"d17協商賠償支付對象_公庫"	INTEGER,
	"d18協商賠償支付對象_公益團體"	INTEGER,
	"d19協商賠償支付對象_地方自治團體"	INTEGER,
	"d20協商賠償支付金額"	REAL,
	"d21宣告沒收適用法律_刑法第38條第1項"	INTEGER,
	"d22宣告沒收適用法律_刑法第38條第2項"	INTEGER,
	"d23宣告沒收適用法律_刑法第38條第3項"	INTEGER,
	"d24宣告沒收適用法律_刑法第38_1條第1項"	INTEGER,
	"d25宣告沒收適用法律_刑法第38_1條第2項"	INTEGER,
	"d26宣告沒收適用法律_刑法第38_1條第2項第1款"	INTEGER,
	"d27宣告沒收適用法律_刑法第38_1條第2項第2款"	INTEGER,
	"d28宣告沒收適用法律_刑法第38_1條第2項第3款"	INTEGER,
	"d29沒收資料_沒收客體"	TEXT,
	"d30沒收資料_沒收金額"	REAL,
	"d31是否宣告緩刑"	INTEGER,
	"d32宣告緩刑附記應遵收事項_向被害人道歉"	INTEGER,
	"d33宣告緩刑附記應遵收事項_立悔過書"	INTEGER,
	"d34宣告緩刑附記應遵收事項_向被害人支付相當數額之財產或非財產上之損害賠償"	INTEGER,
	"d35向被害人支付損害賠償金額"	REAL,
	"d36宣告緩刑附記應遵收事項_向公庫支付一定之金額"	INTEGER,
	"d37向公庫支付金額"	REAL,
	"d38宣告緩刑附記應遵收事項_向指定之政府機關構行政法人社區公益機構或團體提供40小時以上240小時以下之義務勞務"	INTEGER,
	"d39宣告緩刑附記應遵收事項_完成戒癮治療精神治療心理輔導或其他適當之處遇措施"	INTEGER,
	"d40宣告緩刑附記應遵收事項_保護被害人安全之必要命令"	INTEGER,
	"d41宣告緩刑附記應遵收事項_預防再犯所為之必要命令"	INTEGER,
	"d42違反家暴法緩刑期間應遵守事項_第38條第2項第1款禁止實施家庭暴力"	INTEGER,
	"d43違反家暴法緩刑期間應遵守事項_第38條第2項第3款強制遷出"	INTEGER,
	"d44反家暴法緩刑期間應遵守事項第38條第2項第2款禁止騷擾等行為"	INTEGER,
	"d45違反家暴法緩刑期間應遵守事項第38條第2項第5款強制戒癮治療"	INTEGER,
	"d46違反家暴法緩刑期間應遵守事項第38條第2項第5款強制精神治療"	INTEGER,
	"d47違反家暴法緩刑期間應遵守事項第38條第2項第5款強制心理輔導"	INTEGER,
	"d48違反家暴法緩刑期間應遵守事項第38條第2項第5款強制其他治療輔導"	INTEGER,
	"d49違反家暴法緩刑期間應遵守事項第38條第2項第6款其他必要保護被害人等措施"	INTEGER,
	"d50違反家暴法緩刑期間應遵守事項第38條第2項第4款強制遠離"	INTEGER,
	"d51違反家暴法緩刑期間應遵守事項第38條第2項第5款強制認知教育輔導"	INTEGER,
	"d52違反家暴法緩刑期間應遵守事項第38條第2項第5款強制親職教育輔導"	INTEGER,
	"d53違反家暴法緩刑期間應遵守事項第38條第2項第5款舊法其他更生保護事項"	INTEGER,
	"d54減刑條例年度1"	INTEGER,
	"d55減刑條例年度2"	INTEGER,
	"d56減刑條例年度3"	INTEGER,
	"d57減刑條例年度4"	INTEGER,
	"d58應執行刑1020401前_主刑"	TEXT,
	"d59應執行刑1020401前_有期徒刑"	TEXT,
	"d60定應執行刑_有期徒刑得易科"	TEXT,
	"d61定應執行刑_有期徒刑不得易科逾6月"	TEXT,
	"d62定應執行刑_有期徒刑不得易科6月以下"	TEXT,
	"d63定應執行刑_拘役"	INTEGER,
	"d64定應執行刑_罰金類別"	TEXT,
	"d65定應執行刑_罰金"	REAL,
	"d66定應執行刑_無期徒刑或死刑"	TEXT,
	"d67是否為累犯"	INTEGER,
	"d68是否有刑法第91條之1第1項審前鑑定"	INTEGER,
	"d69被告終結情形"	TEXT,
	"d70上訴人別1"	TEXT,
	"d71上訴人別2"	TEXT,
	"c28裁判書ID"	INTEGER,
	"Case_ID"	INTEGER NOT NULL,
	"Defendant_ID"	INTEGER UNIQUE,
	PRIMARY KEY("Defendant_ID" AUTOINCREMENT),
	FOREIGN KEY("Case_ID") REFERENCES "Cases"("Case_ID")
);
CREATE TABLE IF NOT EXISTS "Charges" (
	"ch1控制碼"	INTEGER,
	"ch2刑事法令"	TEXT,
	"ch3刑事法令_條"	INTEGER,
	"ch4刑事法令_之條"	INTEGER,
	"ch5刑事法令_條_段"	INTEGER,
	"ch6刑事法令_項"	INTEGER,
	"ch7刑事法令_項_段"	INTEGER,
	"ch8刑事法令_款"	INTEGER,
	"ch9修法年月"	TEXT,
	"ch10被告罪名裁判結果"	TEXT,
	"ch11宣告有期徒刑"	TEXT,
	"ch12拘役日數"	INTEGER,
	"ch13罰金金額"	REAL,
	"ch14是否得易科"	INTEGER,
	"ch15是否褫奪公權"	INTEGER,
	"ch16罪犯類型_少年犯"	INTEGER,
	"ch17罪犯類型_幫助犯"	INTEGER,
	"ch18罪犯類型_未遂犯"	INTEGER,
	"ch19罪犯類型_家庭暴力"	INTEGER,
	"Defendant_ID"	INTEGER,
	"Charge_ID"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("Charge_ID" AUTOINCREMENT),
	FOREIGN KEY("Defendant_ID") REFERENCES "Defendants"("Defendant_ID")
);
CREATE TABLE IF NOT EXISTS "Aggravation" (
	"a1控制碼"	INTEGER,
	"a2量刑加重"	TEXT,
	"a3"	TEXT,
	"a4"	TEXT,
	"a5"	TEXT,
	"a6"	TEXT,
	"a7"	TEXT,
	"Charge_ID"	INTEGER,
	FOREIGN KEY("Charge_ID") REFERENCES "Charges"("Charge_ID")
);
CREATE TABLE IF NOT EXISTS "Commutation" (
	"r1控制碼"	INTEGER,
	"r2量刑減輕"	TEXT,
	"r3"	TEXT,
	"r4"	TEXT,
	"r5"	TEXT,
	"r6"	TEXT,
	"r7"	TEXT,
	"Charge_ID"	INTEGER,
	FOREIGN KEY("Charge_ID") REFERENCES "Commutation"("Charge_ID")
);
CREATE TABLE IF NOT EXISTS "ThirdPersonForfeiture" (
	"t1控制碼"	INTEGER,
	"t2沒收程序裁判結果"	TEXT,
	"t3宣告沒收適用法律_刑法第38條第1項_違禁物"	INTEGER,
	"t4宣告沒收適用法律_刑法第38條第3項_犯罪工具產物"	INTEGER,
	"t5宣告沒收適用法律_刑法第38_1條第2項_犯罪所得"	INTEGER,
	"t6宣告沒收適用法律_刑法第38_1條第2項第1款_犯罪所得"	INTEGER,
	"t7宣告沒收適用法律_刑法第38_1條第2項第2款_犯罪所得"	INTEGER,
	"t8宣告沒收適用法律_刑法第38_1條第2項第3款_犯罪所得"	INTEGER,
	"t9沒收資料_沒收客體"	TEXT,
	"t10沒收資料_沒收金額"	INTEGER,
	"c28裁判書ID"	TEXT,
	"Case_ID"	INTEGER NOT NULL,
	"TPF_ID"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("TPF_id" AUTOINCREMENT),
	FOREIGN KEY("Case_ID") REFERENCES "Cases"("Case_ID")
);
CREATE TABLE IF NOT EXISTS "ThirdPersonForfeitureLaw" (
	"tl1控制碼"	INTEGER,
	"tl2刑事法令"	TEXT,
	"tl3刑事法令_條"	INTEGER,
	"tl4刑事法令_之條"	INTEGER,
	"tl5刑事法令_條_段"	INTEGER,
	"tl6刑事法令_項"	INTEGER,
	"tl7刑事法令_項_段"	INTEGER,
	"tl8刑事法令_款"	INTEGER,
	"TPF_ID"	INTEGER,
	"TPF_law_ID"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("TPF_law_ID" AUTOINCREMENT),
	FOREIGN KEY("TPF_ID") REFERENCES "ThirdPersonForfeiture"("TPF_ID")
);
COMMIT;
